config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users

  scope constraints: {id: /.+/} do
    resources :ht_users
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_approval_requests
  end

  root "ht_users#index"

  scope format: false, constraints: {id: /.+/} do
    resources :ht_institutions
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_contacts
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_contact_types
  end

  get "/ht_downloads", to: "ht_downloads#index", as: :ht_downloads

  scope constraints: {id: /.+/} do
    resources :ht_logs
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_registrations do
      member do
        get "preview"
        post "mail"
        post "finish"
        post "approve"
      end
    end
  end

  get "/login", to: "session#new", as: "login"
  post "/login", to: "session#create", as: "login_as"
  unless Rails.env.production?
    match "/logout", to: "session#destroy", as: "logout", via: [:get, :post]
  end

  get "/approve/:token", to: "approval#new", as: :approve

  get "/submit_registration/:token", to: "submit_registration#new", as: :submit_registration

  unless Rails.env.production?
    get "Shibboleth.sso/Login", controller: :fake_shib, as: :fake_shib, action: :new
  end
end

app/models/ht_user.rb
# frozen_string_literal: true

require "forwardable"

class HTUserRenewalError < StandardError
  attr_reader :type
  TYPES = %i[missing].freeze

  def initialize(msg = "Renewal Error", type:)
    @type = type
    super(msg)
  end
end

class HTUser < ApplicationRecord
  ROLES = %i[corrections cataloging ssdproxy crms quality staffdeveloper staffsysadmin replacement ssd resource_sharing].freeze
  USERTYPES = %i[staff external student].freeze
  ACCESSES = %i[total normal].freeze
  EXPIRES_TYPES = ExpirationDate::EXPIRES_TYPE.collect { |k, _v| k }.freeze
  self.primary_key = "email"

  belongs_to :ht_institution, foreign_key: :inst_id, primary_key: :inst_id
  has_one :ht_count, foreign_key: :userid, primary_key: :userid
  has_many :ht_logs, -> { HTLog.ht_user }, foreign_key: :objid, primary_key: :email
  has_many :ht_approval_request, -> { order(HTApprovalRequest.most_recent_order) }, foreign_key: :userid, primary_key: :email
  has_many :ht_registration, foreign_key: :applicant_email, primary_key: :email

  validates :iprestrict, presence: true, unless: :mfa
  validate :validate_iprestrict
  validate :validate_expires

  validates :email, presence: true, uniqueness: true
  validates :userid, presence: true
  validates :expires, presence: true
  validates :inst_id, presence: true
  validates :approver, presence: true

  validates :mfa, absence: true, unless: -> { ht_institution.shib_authncontext_class.present? }

  scope :active, -> { where("expires > CURRENT_TIMESTAMP") }
  scope :expired, -> { where("expires <= CURRENT_TIMESTAMP") }
  scope :expiring_soon, -> {
    where("DATE_SUB(expires,INTERVAL #{ExpirationDate::EXPIRES_SOON_IN_DAYS} DAY) <= CURRENT_TIMESTAMP")
      .where("expires > CURRENT_TIMESTAMP")
  }

  after_save :clean_requests

  # Checkpoint override
  def resource_id
    email
  end

  # Work around the fact that Rails' built-in typecasting clobbers various bogus
  # dates into nil. https://stackoverflow.com/a/35553281
  def validate_expires
    if expires.nil? && respond_to?(:expires_before_type_cast)
      raw_data = expires_before_type_cast.to_s
      begin
        Time.zone.parse(raw_data)
      rescue
        errors.add(:expires, :invalid)
      end
    end
  end

  # Update expiration_date only if it already exists, because factorybot updates
  # stuff in order and we might not have the expire_type yet
  # This seems like a dumb way to deal with the testing framework, but I'm
  # not sure what else to do. Maybe just reorder the factory definition
  # and put a note in there?
  def expires=(val)
    self[:expires] = val
    @expiration_date = expiration_date(:force_update) unless @expiration_date.nil?
    expires
  end

  def expiration_date(force_update = false)
    if force_update || @expiration_date.nil?
      type = expire_type
      date = expires
      @expiration_date = ExpirationDate.new(date, type.to_s)
    end
    @expiration_date
  end

  # iprestrict is in the database as an escaped IPv4 regex e.g., ^127\.0\.0\.1$
  # For the UI we strip out and restore the ^/./$ characters
  # Since multiple addresses are permitted if separated by OR (|) this value is
  # an array.
  def iprestrict
    return nil unless self[:iprestrict]

    IPRestriction.from_regex(self[:iprestrict]).addrs
  end

  def iprestrict=(vals)
    self[:iprestrict] = if vals
      IPRestriction.from_string(vals).to_regex
    end
  end

  ## Forward some stuff to @expiration_date

  # Display datetime without UTC suffix or just date
  # This is used by the approval request mailer which is not yet really locale-aware.
  # Otherwise we would ditch it.
  def expires_string
    expiration_date.to_s
  end

  # How many days until expiration?
  # @return [Number] days until expiration
  def days_until_expiration
    expiration_date.days_until_expiration
  end

  # Is this person expiring "soon" (based on the config)?
  # @return [Boolean]
  def expiring_soon?
    expiration_date.expiring_soon?
  end

  def expired?
    expiration_date.expired?
  end

  def extend_by_default_period!
    self.expires = expiration_date.default_extension_date.to_date
  end

  def institution
    ht_institution&.name
  end

  # Validate the fully-escaped ip address(es) as saved in the model.
  def validate_iprestrict
    return unless self[:iprestrict].present?

    begin
      IPRestriction.from_regex(self[:iprestrict]).validate
    rescue IPRestrictionError => e
      errors.add :iprestrict, e.type, addr: e.address
    end
  end

  def renew!
    extend_by_default_period!
    save!
  end

  # Called when a user is renewed via approval request, and when a user's expiration is edited.
  # If `force`, makes sure there is an appropriate approval request in place,
  # creating one out of thin air if necessary.
  # Note: this does not actually renew the user (i.e., bump `ht_user.expiration_date`);
  # that is the caller's responsibility to do if needed. (Earlier versions called `renew!` here
  # but could cause double renewal if the user was being manually edited.)
  def add_or_update_renewal(approver:, force: false)
    req = ht_approval_request.approved.not_renewed.first

    if force
      req ||= ht_approval_request.not_renewed.first
      req ||= HTApprovalRequest.new(approver: approver, ht_user: self)
    end

    raise(HTUserRenewalError.new(type: :no_approved_request)) unless req

    req.renewed = Time.zone.now
    req.save!
  end

  def csv_cols
    attributes.keys + ["inst_name"]
  end

  def csv_vals
    attributes.values + [institution]
  end

  private

  def clean_requests
    if saved_change_to_approver? || (saved_change_to_expires? &&
                                     expiration_date(true).days_until_expiration < 1)
      ht_approval_request.not_approved.not_renewed.destroy_all
    end
  end
end

app/controllers/ht_users_controller.rb
# frozen_string_literal: true

class HTUsersController < ApplicationController
  before_action :fetch_user, only: %i[show edit]

  PERMITTED_UPDATE_FIELDS = %i[userid displayname activitycontact approver authorizer
    usertype role access expires expire_type iprestrict mfa].freeze

  def index
    users = HTUser.includes(:ht_institution, :ht_approval_request).order("ht_institutions.name").order(HTApprovalRequest.most_recent_order)
    @users = users.active.map { |u| presenter u }
    @expired_users = users.expired.map { |u| presenter u }
    respond_to do |format|
      format.html
      format.csv do
        file_name = (params[:file_name] || "ht_users") + ".csv"
        send_data users_csv, filename: file_name
      end
    end
  end

  def update
    @user = HTUser.find(params[:id])

    # Any extension of term counts as a renewal for our purposes.
    renewing = user_params[:expires].present? && user_params[:expires] > @user.expires.to_date.to_s

    if @user.update(user_params)
      @user.add_or_update_renewal(approver: current_user.id, force: true) if renewing
      log_action(@user, user_params)
      update_user_success
    else
      update_user_failure
    end
  end

  private

  def presenter(user)
    HTUserPresenter.new(user, controller: self, action: params[:action].to_sym)
  end

  def update_user_failure
    flash.now[:alert] = @user.errors.full_messages.to_sentence
    fetch_user
    render "edit"
  end

  def update_user_success
    flash[:notice] = t "ht_users.update.success"
    redirect_to @user
  end

  def fetch_user
    @user = presenter HTUser.joins(:ht_institution).find(params[:id])
  end

  def user_params
    @user_params ||= begin
      p = params.require(:ht_user).permit(*PERMITTED_UPDATE_FIELDS)
      (p[:mfa] == "1") ? p.merge({iprestrict: nil}) : p
    end
  end

  def users_csv
    require "csv"
    all_users = @users + @expired_users
    CSV.generate do |csv|
      csv << all_users.first.csv_cols
      all_users.each do |user|
        if params[:role_filter]&.include?(user.role)
          next
        end
        csv << user.csv_vals
      end
    end
  end
end

app/views/ht_users/edit.html.erb
<div id="maincontent" class="row">
  <h1><%= "#{@user.displayname}" %></h1>

  <script>
    var save_ip = '';
    function check_mfa() {
      if ($('#ht_user_mfa').prop('checked')) {
        save_ip = $('#ht_user_iprestrict').val();
        $('#ht_user_iprestrict').val('');
        $('#ht_user_iprestrict').attr('disabled', true);
      }
      else {
        if (save_ip.length > 0) {
          $('#ht_user_iprestrict').val(save_ip);
        }
        $('#ht_user_iprestrict').attr('disabled', false);
      }
    }

    $('#edit_ht_user_form').submit(function() {
      $('#ht_user_iprestrict').attr('disabled', false);
    })

    // Get the date from the date input and do some maths with it.
    // If the current date is >= the "danger" cutoff then add the danger class,
    // otherwise remove it.
    // Also, the "Expire Now" button is disabled when user is already expired,
    // so enable it once the date changes.
    function check_expiration() {
      var expires_soon_in_days = <%= ExpirationDate::EXPIRES_SOON_IN_DAYS %>;
      var result = new Date(Date.parse($('#ht_user_expires').val()));
      result.setDate(result.getDate() - expires_soon_in_days);
      if (new Date(Date.now()) >= result) {
        $('#ht_user_expires').addClass('bg-danger');
      } else {
        $('#ht_user_expires').removeClass('bg-danger');
      }
      $('#ht_user_expire_now').prop('disabled', false);
    }

    function set_expiration(date) {
      $('#ht_user_expires').val(date);
      check_expiration();
    }
  </script>

  <%= form_with(model: @user, local: true, id: 'edit_ht_user_form') do |form| %>
    <dl class="row">
      <% @user.all_fields.each do |field| %>
        <dt class="col-sm-3"><%= @user.field_label field, form: form %></dt>
        <dd class="col-sm-9"><%= @user.field_value field, form: form %></dd>
      <% end %>
    </dl>
    <hr/>
    <dl class="row">
      <% @user.ht_counts_fields.each do |field| %>
        <dt class="col-sm-3"><%= @user.field_label field, form: form %></dt>
        <dd class="col-sm-9"><%= @user.field_value field, form: form %></dd>
      <% end %>
    </dl>
    <%= form.submit t(".submit_changes"), class: 'btn btn-primary' %>
    <%= link_to t(".cancel"), ht_user_path(@user), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/ht_users/index.html.erb
<div id="maincontent">
  <h1><%= t ".users" %></h1>

  <% fields = HTUserPresenter::INDEX_FIELDS %>
  <%= form_tag(ht_approval_requests_path, method: :post) do %>

  <div class="dropdown">
    <button class="btn btn-info text-light dropdown-toggle" type="button" id="download-menu"
      data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= t(".download_csv") %>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="download-menu">
      <li>
        <%= link_to t(".download_csv_non_atrs"), ht_users_url(format: :csv, role_filter: [:ssd, :ssdproxy], file_name: "non_atrs_users"), class: "dropdown-item" %>
      </li>
      <li>
        <%= link_to t(".download_csv_all"), ht_users_url(format: :csv, file_name: "all_users"), class: "dropdown-item" %>
      </li>
    </ul>
  </div>

  <h2 class="float-start"><%= t ".active_users" %></h2>
  <table
    id="active_users"
    class="table table-striped"
    data-height="460"
    data-locale="<%= language_region_locale %>"
    data-search="true"
    data-show-columns="true"
    data-show-search-clear-button="true"
    data-toggle="table"
    data-virtual-scroll="true"
  >
    <thead class="thead-dark">
    <tr>
      <% if can?(:create, HTApprovalRequest) || can?(:edit, HTUser) %>
        <th data-sortable="true"><%= t ".select" %></th>
      <% end %>
      <% fields.each do |field| %>
        <th data-sortable="true"><%= HTUserPresenter.field_label field %></th>
      <% end %>
    </tr>
    </thead>

    <% @users.each do |u| %>
      <tr>
        <% if can?(:create, HTApprovalRequest) || can?(:edit, HTUser) %>
          <td><%= u.select_for_renewal_checkbox %></td>
        <% end %>
        <% fields.each do |field| %>
          <td><%= u.field_value field %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <br/>

  <% if can?(:create, HTApprovalRequest)  %>
    <%= button_tag t(".create_approval_requests"), type: 'submit', name: 'submit_requests', class: 'btn btn-primary my-2' %>
  <% end %>
  <% if can?(:edit, HTUser) %>
    <%= button_tag t(".renew_selected_users"), type: 'submit', name: 'submit_renewals', class: 'btn btn-primary my-2' %>
  <% end %>

  <% end # form_tag %>

  <h2 class="float-start"><%= t ".expired_users" %></h2>
  <table
    id="expired_users"
    class="table table-striped"
    data-height="460"
    data-locale="<%= language_region_locale %>"
    data-search="true"
    data-show-columns="true"
    data-show-search-clear-button="true"
    data-thead-classes="thead-dark"
    data-toggle="table"
    data-virtual-scroll="true"
  >
    <thead>
    <tr>
      <% fields.each do |field| %>
        <th data-sortable="true"><%= HTUserPresenter.field_label field %></th>
      <% end %>
    </tr>
    </thead>
    <% @expired_users.each do |u| %>
      <tr>
        <% fields.each do |field| %>
          <td><%= u.field_value field %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/ht_users/show.html.erb
<div id="maincontent" class="row">
  <h1><%= @user.displayname %></h1>

  <div class="col-sm-6">
    <dl class="row">
      <% @user.all_fields.each do |field| %>
        <dt class="col-sm-3"><%= @user.field_label field %></dt>
        <dd class="col-sm-9"><%= @user.field_value field %></dd>
      <% end %>
    </dl>
    <hr/>
    <dl class="row">
      <% @user.ht_counts_fields.each do |field| %>
        <dt class="col-sm-3"><%= @user.field_label field %></dt>
        <dd class="col-sm-9"><%= @user.field_value field %></dd>
      <% end %>
    </dl>

    <% if can?(:edit, HTUser) %>
      <%= link_to t('.edit'), edit_ht_user_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>