config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users

  scope constraints: {id: /.+/} do
    resources :ht_users
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_approval_requests
  end

  root "ht_users#index"

  scope format: false, constraints: {id: /.+/} do
    resources :ht_institutions
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_contacts
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_contact_types
  end

  get "/ht_downloads", to: "ht_downloads#index", as: :ht_downloads

  scope constraints: {id: /.+/} do
    resources :ht_logs
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_registrations do
      member do
        get "preview"
        post "mail"
        post "finish"
        post "approve"
      end
    end
  end

  get "/login", to: "session#new", as: "login"
  post "/login", to: "session#create", as: "login_as"
  unless Rails.env.production?
    match "/logout", to: "session#destroy", as: "logout", via: [:get, :post]
  end

  get "/approve/:token", to: "approval#new", as: :approve

  get "/submit_registration/:token", to: "submit_registration#new", as: :submit_registration

  unless Rails.env.production?
    get "Shibboleth.sso/Login", controller: :fake_shib, as: :fake_shib, action: :new
  end
end

app/models/ht_approval_request.rb
# frozen_string_literal: true

class HTApprovalRequest < ApplicationRecord
  self.primary_key = "id"
  self.table_name = "ht_web.otis_approval_requests"

  def self.expiration_date
    Date.today - 1.week
  end

  # Make sure that the most recent and most "incomplete" request comes first when fetching request for user
  # If we had created/updated timestamps we could use those.
  def self.most_recent_order
    {
      Arel.sql("sent IS NULL") => :desc, :sent => :desc,
      Arel.sql("received IS NULL") => :desc, :received => :desc,
      Arel.sql("renewed IS NULL") => :desc, :renewed => :desc
    }
  end
  # "Active" requests that may be subject to further action
  scope :not_renewed, -> { where(renewed: nil) }
  # "Inactive" requests that are only of historical interest
  scope :renewed, -> { where.not(renewed: nil) }
  scope :expired, -> { where(renewed: nil, received: nil).where.not(sent: nil).where("sent < ?", HTApprovalRequest.expiration_date) }
  scope :active, -> { where(renewed: nil, received: nil).where.not(sent: nil).where("sent >= ?", HTApprovalRequest.expiration_date) }
  scope :for_approver, ->(approver) { where(approver: approver).order(:sent, :received, :renewed) }
  scope :for_user, ->(user) { where(userid: user).order(:sent, :received, :renewed) }
  scope :most_recent, ->(user) { for_user(user).order(most_recent_order) }
  scope :not_approved, -> { where(received: nil) }
  scope :approved, -> { where.not(received: nil) }
  validates :approver, presence: true
  validates :ht_user, uniqueness: {
    conditions: -> { not_renewed }
  }
  validates :token_hash, presence: true, if: :sent
  validates :sent, presence: true, if: :token_hash
  validate :sent_before_received
  belongs_to :ht_user, foreign_key: :userid, primary_key: :email

  def sent_before_received
    return unless self[:sent].present? && self[:received].present? && self[:sent] > self[:received]

    errors.add(:sent, :after_received)
  end

  def self.digest(tok)
    Digest::SHA256.base64digest(Base64.decode64(tok))
  end

  def self.find_by_token(tok)
    find_by_token_hash(digest(tok))
  end

  # This is the bit that goes to the approver, just a gob of b64 data acting as a 'password'
  def token
    @token ||= SecureRandom.urlsafe_base64 16
  end

  # Display datetime without UTC suffix or just date
  def sent(short: false)
    short ? self[:sent]&.strftime("%Y-%m-%d") : self[:sent]&.to_fs(:db)
  end

  def sent=(value)
    self[:sent] = value
    self[:token_hash] = self.class.digest(token)
  end

  def received(short: false)
    date_field(:received, short: short)
  end

  def renewed(short: false)
    date_field(:renewed, short: short)
  end

  # Approval requests are good for a week once the e-mail is sent.
  def expired?
    self[:sent].present? && self[:sent] < HTApprovalRequest.expiration_date
  end

  # Expired or unsent
  def mailable?
    %i[unsent expired].include? renewal_state
  end

  def renewal_state
    return :renewed if self[:renewed].present?

    return :approved if self[:received].present?

    return :expired if expired?

    return :sent if self[:sent].present?

    :unsent
  end

  private

  def date_field(field, short: false)
    if short
      self[field]&.strftime("%Y-%m-%d")
    else
      self[field]&.to_fs(:db)
    end
  end
end

app/controllers/ht_approval_requests_controller.rb
# frozen_string_literal: true

class HTApprovalRequestsController < ApplicationController
  before_action :fetch_requests, only: %i[show update edit]

  def create
    if params[:submit_requests]
      @added_users = add_requests(params[:ht_users])
      if @added_users.any?
        flash[:notice] = t ".added_users", users: @added_users.to_sentence
      end
      session[:added_users] = @added_users
    end
    if params[:submit_renewals]
      @renewed_users = add_renewals(params[:ht_users])
      if @renewed_users.any?
        flash[:notice] = t ".renewed_users", users: @renewed_users.to_sentence
      end
      session[:renewed_users] = @renewed_users
    end
    if params[:delete_expired]
      deleted = delete_expired
      if deleted.any?
        flash[:notice] = t ".deleted_users", users: deleted.to_sentence
      end
    end
    redirect_to action: :index
  end

  def index
    requests = HTApprovalRequest.order("approver")
    @incomplete_reqs = requests.not_renewed.map { |r| presenter r }
    @complete_reqs = requests.renewed.map { |r| presenter r }
    @added_users = session[:added_users] || []
    @renewed_users = session[:renewed_users] || []
    session.delete :added_users
    session.delete :renewed_users
  end

  def update
    begin
      ApprovalRequestMailer.with(reqs: @reqs, base_url: request.base_url,
        email_body: params[:email_body], subject: params[:subject]).approval_request_email.deliver_now
      @reqs.each do |req|
        next unless req.mailable?

        UserMailer.with(req: req).approval_request_user_email.deliver_now
        req.sent = Time.zone.now
        req.save!
      end
      flash[:notice] = t ".messages_sent"
      # This is for debugging and system testing only
      unless Rails.env.production?
        urls = @reqs.map { |req| approve_url req.token, locale: nil }.join(", ")
        flash[:notice] = "Message sent: #{urls}"
      end
    rescue => e
      flash[:alert] = e.message
    end
    redirect_to action: "show"
  end

  def status_counts
    @reqs.group_by(&:renewal_state).transform_values(&:length)
  end

  def edit
    @preview = true
    @email_body = render_to_string partial: "shared/approval_request_body"
  end

  private

  def presenter(user)
    HTApprovalRequestPresenter.new(user, controller: self, action: params[:action].to_sym)
  end

  def fetch_requests
    @reqs = HTApprovalRequest.for_approver(params[:id]).not_renewed.map do |r|
      presenter r
    end
  end

  # Add an approval request for selected users.
  # If unrenewed one already exists, silently skip over it.
  # Returns an Array of ht_user emails added to requests.
  def add_requests(emails)
    if emails.nil? || emails.empty?
      flash[:alert] = t "ht_approval_requests.create.no_selection"
      return []
    end
    adds = []
    emails.each do |e|
      next if HTApprovalRequest.where(userid: e, renewed: nil).count.positive?

      begin
        add_request e
        adds << e
      rescue => e
        flash[:alert] = e.message
      end
    end
    adds
  end

  def add_request(email)
    u = HTUser.find(email)
    HTApprovalRequest.new(ht_user: u, approver: u.approver).save!
  end

  def add_renewals(emails)
    if emails.nil? || emails.empty?
      flash[:alert] = "No users selected"
      return []
    end
    adds = []
    emails.each do |e|
      ht_user = HTUser.find(e)
      ht_user.add_or_update_renewal(approver: current_user.id)
      ht_user.renew!
      adds << e
    rescue HTUserRenewalError => err
      flash[:alert] = t ".errors.#{err.type}", user: e
    end
    adds
  end

  def delete_expired
    deleted = HTApprovalRequest.expired.map(&:userid)
    HTApprovalRequest.expired.destroy_all
    deleted
  end
end

app/views/ht_approval_requests/edit.html.erb
<script>
window.addEventListener("load", (e)=>{
  ClassicEditor
    .create( document.querySelector( '#email-editor' ), {
        licenseKey: 'GPL',
        plugins: [ Essentials, Bold, Italic, Font, Paragraph ],
        toolbar: [
            'undo', 'redo', '|', 'bold', 'italic', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor'
        ]
    } )
    .then( editor => {
        console.log( editor );
    } )
    .catch( error => {
        console.error( error );
    } );
});
</script>

<div id="maincontent" class="row">
  <h1><%= t ".requests_for", approver: params[:id] %></h1>

  <% if @reqs.count == 0 %>
    <%= t ".no_requests", approver: params[:id] %>
  <% else %>
    <ul class="list-group">
      <% @reqs.each do |req| %>
        <li class="list-group-item">
          <%= req.userid %>
          <%= req.badge %>
        </li>
      <% end %>
    </ul>

    <!-- MAIL PREVIEW -->
    <% counts = controller.status_counts %>
    <% if counts[:unsent]&.positive? || counts[:expired]&.positive? %>
      <%= form_tag ht_approval_request_path, method: :put do %>
        <div class="card">
          <div class="card-body">
            <div class="card-title"><%= t ".email_preview" %></div>
            <%= label_tag "subject", t(".subject") %>
            <%= text_field_tag "subject", ApprovalRequestMailer.subject, size: 60 %>
            <textarea id="email-editor" data-editor="ClassicEditor" name="email_body">
              <%= @email_body %>
            </textarea>
          </div>
          <div class="card-body">
            <!-- Turn off locale setting since this is part of mail preview -->
            <!-- e-mail content language is orthogonal to UI language -->
            <% I18n.with_locale(I18n.default_locale) do %>
              <%= render 'shared/approval_request_user_table' %>
            <% end %>
          </div>
        </div>
        <% label = counts[:expired]&.positive? ? t(".resend") : t(".send") %>
        <%= submit_tag label, class: 'btn btn-primary' %>
        <%= link_to t(".cancel"), ht_approval_request_path(@reqs[0].approver), class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/ht_approval_requests/index.html.erb
<div id="maincontent">
  <h1><%= t ".approval_requests" %></h1>
  <% if can?(:edit, HTApprovalRequest) %>
    <p><%= t ".instructions" %></p>
  <% end %>

  <% fields = HTApprovalRequestPresenter::INDEX_FIELDS %>
  <%= form_tag(ht_approval_requests_path, method: :post) do %>

  <h2 class="float-start"><%= t ".active_requests" %></h2>
  <table
    id="active-requests"
    class="table table-striped"
    data-height="460"
    data-locale="<%= language_region_locale %>"
    data-search="true"
    data-show-columns="true"
    data-show-search-clear-button="true"
    data-toggle="table"
    data-virtual-scroll="true"
  >
    <thead class="thead-dark">
    <tr>
      <th data-sortable="false"><%= t ".select" %></th>
      <% fields.each do |field| %>
        <th data-sortable="true"><%= HTApprovalRequestPresenter.field_label field %></th>
      <% end %>
    </tr>
    </thead>

    <% @incomplete_reqs.each do |req| %>
      <%= tag(:tr, class: @added_users.include?(req.userid) ? :success : nil) %>
        <td>
          <% if can?(:edit, HTApprovalRequest) %>
            <%= req.select_for_renewal_checkbox %>
          <% end %>
        </td>
        <td>
          <% if can?(:edit, HTApprovalRequest) %>
            <%= req.approver_link %>
          <% else %>
            <%= req.approver %>
          <% end %>
        </td>
        <td>
          <%= req.userid_link(label: can?(:edit, HTApprovalRequest)) %>
        </td>
        <td class="text-nowrap">
          <%= req.sent(short: true) %>
          <% if req.renewal_state == :expired %>
            <%= req.badge %>
          <% end %>
        </td>
        <td><%= req.received(short: true) %></td>
        <td>
          <%= req.renewed(short: true) %>
        </td>
      </tr>
    <% end %>
  </table>
  <br/>
  <% if can?(:edit, HTUser) %>
    <%= submit_tag t(".renew_selected"), name: 'submit_renewals', class: 'btn btn-primary my-2' %>
  <% end %>
  <% if can?(:destroy, HTApprovalRequest) && HTApprovalRequest.expired.any? %>
    <%= submit_tag t(".delete_expired"), name: 'delete_expired', class: 'btn btn-danger my-2',
                   data: { confirm: t(".confirm_delete", count: HTApprovalRequest.expired.count) } %>
  <% end %>
  <% end # form-tag %>
  <h2 class="float-start"><%= t ".inactive_requests" %></h2>
  <table
    id="inactive-requests"
    class="table table-striped"
    data-height="460"
    data-locale="<%= language_region_locale %>"
    data-search="true"
    data-show-columns="true"
    data-show-search-clear-button="true"
    data-toggle="table"
    data-virtual-scroll="true"
  >
    <thead class="thead-dark">
    <tr>
      <% fields.each do |field| %>
        <th data-sortable="true"><%= HTApprovalRequestPresenter.field_label field %></th>
      <% end %>
    </tr>
    </thead>

    <% @complete_reqs.each do |req| %>
      <%= tag(:tr, class: @renewed_users.include?(req.userid) ? :success : nil) %>
        <td><%= req.approver %></td>
        <td><%= link_to req.userid, ht_user_path(req.userid) %></td>
        <td><%= req.sent(short: true) %></td>
        <td><%= req.received(short: true) %></td>
        <td><%= req.renewed(short: true) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/ht_approval_requests/show.html.erb
<div id="maincontent" class="row">
  <h1><%= t ".requests_for", approver: params[:id] %></h1>

  <% if @reqs.count == 0 %>
    <%= t ".no_requests", approver: params[:id] %>
  <% else %>
    <ul class="list-group">
    <% @reqs.each do |req| %>
      <li class="list-group-item">
        <%= req.userid %>
        <%= req.badge %>
      </li>
    <% end %>
    </ul>
    <% counts = controller.status_counts %>
    <% if counts[:unsent]&.positive? || counts[:expired]&.positive? %>
      <%= link_to t(".edit"), edit_ht_approval_request_path, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>