config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users

  scope constraints: {id: /.+/} do
    resources :ht_users
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_approval_requests
  end

  root "ht_users#index"

  scope format: false, constraints: {id: /.+/} do
    resources :ht_institutions
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_contacts
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_contact_types
  end

  get "/ht_downloads", to: "ht_downloads#index", as: :ht_downloads

  scope constraints: {id: /.+/} do
    resources :ht_logs
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_registrations do
      member do
        get "preview"
        post "mail"
        post "finish"
        post "approve"
      end
    end
  end

  get "/login", to: "session#new", as: "login"
  post "/login", to: "session#create", as: "login_as"
  unless Rails.env.production?
    match "/logout", to: "session#destroy", as: "logout", via: [:get, :post]
  end

  get "/approve/:token", to: "approval#new", as: :approve

  get "/submit_registration/:token", to: "submit_registration#new", as: :submit_registration

  unless Rails.env.production?
    get "Shibboleth.sso/Login", controller: :fake_shib, as: :fake_shib, action: :new
  end
end

app/controllers/contact_types_controller.rb
# frozen_string_literal: true

class ContactTypesController < ApplicationController
  before_action :fetch_contact_type, only: %i[destroy edit show]

  PERMITTED_UPDATE_FIELDS = %i[name description].freeze
  PERMITTED_CREATE_FIELDS = PERMITTED_UPDATE_FIELDS + %i[id]

  def new
    @contact_type = ContactTypePresenter.new(ContactType.new)
  end

  def index
    contact_types = ContactType.order(:name)
    @contact_types = contact_types.map { |c| ContactTypePresenter.new(c) }
  end

  def update
    @contact_type = ContactType.find(params[:id])
    if @contact_type.update(contact_type_params(PERMITTED_UPDATE_FIELDS))
      log
      flash[:notice] = "Contact type updated"
      redirect_to @contact_type
    else
      flash.now[:alert] = @contact_type.errors.full_messages.to_sentence
      fetch_contact_type
      render :edit
    end
  end

  def create
    @contact_type = ContactType.new(contact_type_params(PERMITTED_CREATE_FIELDS))
    if @contact_type.save
      log
      redirect_to @contact_type, note: "Contact type successfully created"
    else
      flash.now[:alert] = @contact_type.errors.full_messages.to_sentence
      @contact_type = ContactTypePresenter.new(@contact_type)
      render :new
    end
  end

  def destroy
    # Log here, because after #destroy the object becomes invalid
    log params.permit!
    if @contact_type.destroy
      flash[:notice] = "Contact type removed"
      redirect_to contact_types_url
    else
      flash.now[:alert] = @contact_type.errors.full_messages.to_sentence
      render :show
    end
  end

  private

  def log(params = @contact_type_params)
    log_action(@contact_type, params)
  end

  def contact_type_params(permitted_fields)
    @contact_type_params ||= params.require(:contact_type)
      .permit(*permitted_fields)
      .transform_values! { |v| v.present? ? v : nil }
  end

  def fetch_contact_type
    @contact_type = ContactTypePresenter.new(ContactType.find(params[:id]))
  end
end

app/views/contact_types/_form.html.erb
  <h1><%= @contact_type.name %></h1>

  <%= render 'shared/flash_message' %>

  <%= form_with(model: @contact_type, local: true, id: 'edit_contact_type_form') do |form| %>
    <div class="col-sm-6">
      <dl class="dl-horizontal">
        <dt>ID:</dt> <dd><%= @contact_type.id %></dd>

        <dt>Name:</dt>
        <dd><%= form.text_field :name, size: 20 %></dd>

        <dt>Description:</dt> 
        <dd> <%= form.text_area :description, size: "80x4" %> </dd>
      </dl>
      <%= form.submit 'Submit Changes', class: 'btn btn-primary' %>
      <%= @contact_type.cancel_button %>
    </div>

  <% end %>

app/views/contact_types/edit.html.erb
<div id="maincontent" class="row">
  <%= render 'form' %>
</div>

app/views/contact_types/index.html.erb
<div id="maincontent" class="row">

  <%= render 'shared/flash_message' %>

  <h2 class="pull-left">Contact Types</h2>

  <table id="active_users" class="table table-striped" data-toggle="table" data-height="460" data-virtual-scroll="true"
         data-search="true" data-show-search-clear-button="true">
    <thead class="thead-dark">
    <tr>
      <th data-sortable="true">ID</th>
      <th data-sortable="true">Name</th>
      <th data-sortable="true">Description</th>
    </tr>
    </thead>

    <% @contact_types.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.show_link %></td>
        <td><%= c.description %></td>
      </tr>
    <% end %>
  </table>

  <br />

  <% if can?(:create, :contact_types) %>
    <%= link_to 'Add New Contact Type', new_contact_type_path, class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/contact_types/new.html.erb
<div id="maincontent" class="row">
  <h1>New Contact Type</h1>

  <%= render 'form' %>
</div>

app/views/contact_types/show.html.erb
<div id="maincontent" class="row">
  <h1><%= @contact_type.name %></h1>

  <%= render 'shared/flash_message' %>

  <div class="col-sm-6">
    <dl class="dl-horizontal">
      <dt>ID:</dt> <dd><%= @contact_type.id %></dd>
      <dt>Name:</dt> <dd> <%= @contact_type.name %> </dd>
      <dt>Description:</dt> <dd><%= @contact_type.description %></dd>
    </dl>
    <br/>

    <% if can?(:edit, :contact_types) %>
      <%= link_to 'Edit', edit_contact_type_path, class: 'btn btn-primary' %>
    <% end %>
    
    <% if can?(:destroy, :contact_types) %>
      <%= link_to 'Delete Contact Type', contact_type_path, method: :delete, class: 'btn btn-danger',
                  data: { confirm: "Please confirm deletion of contact type \"#{@contact_type.name}\"" } %>
    <% end %>
  </div>
</div>