config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users

  scope constraints: {id: /.+/} do
    resources :ht_users
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_approval_requests
  end

  root "ht_users#index"

  scope format: false, constraints: {id: /.+/} do
    resources :ht_institutions
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_contacts
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_contact_types
  end

  get "/ht_downloads", to: "ht_downloads#index", as: :ht_downloads

  scope constraints: {id: /.+/} do
    resources :ht_logs
  end

  scope format: false, constraints: {id: /.+/} do
    resources :ht_registrations do
      member do
        get "preview"
        post "mail"
        post "finish"
        post "approve"
      end
    end
  end

  get "/login", to: "session#new", as: "login"
  post "/login", to: "session#create", as: "login_as"
  unless Rails.env.production?
    match "/logout", to: "session#destroy", as: "logout", via: [:get, :post]
  end

  get "/approve/:token", to: "approval#new", as: :approve

  get "/submit_registration/:token", to: "submit_registration#new", as: :submit_registration

  unless Rails.env.production?
    get "Shibboleth.sso/Login", controller: :fake_shib, as: :fake_shib, action: :new
  end
end

app/models/approval_request.rb
# frozen_string_literal: true

class ApprovalRequest < ApplicationRecord
  self.primary_key = "id"
  self.table_name = "otis_approval_requests"

  def self.expiration_date
    Date.today - 1.week
  end
  # "Active" requests that may be subject to further action
  scope :not_renewed, -> { where(renewed: nil) }
  # "Inactive" requests that are only of historical interest
  scope :renewed, -> { where.not(renewed: nil) }
  scope :expired, -> { where(renewed: nil, received: nil).where.not(sent: nil).where("sent < ?", ApprovalRequest.expiration_date) }
  scope :for_approver, ->(approver) { where(approver: approver).order(:sent, :received, :renewed) }
  scope :for_user, ->(user) { where(userid: user).order(:sent, :received, :renewed) }
  # Make sure that the most recent and most "incomplete" request comes first when fetching request for user
  # If we had created/updated timestamps we could use those.
  most_recent_order = {Arel.sql("sent IS NULL") => :desc, :sent => :desc,
                       Arel.sql("received IS NULL") => :desc, :received => :desc,
                       Arel.sql("renewed IS NULL") => :desc, :renewed => :desc}
  scope :most_recent, ->(user) { for_user(user).order(most_recent_order) }
  scope :not_approved, -> { where(received: nil) }
  scope :approved, -> { where.not(received: nil) }
  validates :approver, presence: true
  validates :ht_user, uniqueness: {
    conditions: -> { not_renewed },
    message: ->(_object, data) { "#{data[:value]} already has an approval request" }
  }
  validates :token_hash, presence: true, if: :sent
  validates :sent, presence: true, if: :token_hash
  validate :sent_before_received
  belongs_to :ht_user, foreign_key: :userid, primary_key: :email

  def sent_before_received
    return unless self[:sent].present? && self[:received].present? && self[:sent] > self[:received]

    errors.add(:sent, "date sent cannot be after date received")
  end

  def self.digest(tok)
    Digest::SHA256.base64digest(Base64.decode64(tok))
  end

  def self.find_by_token(tok)
    find_by_token_hash(digest(tok))
  end

  # This is the bit that goes to the approver, just a gob of b64 data acting as a 'password'
  def token
    @token ||= SecureRandom.urlsafe_base64 16
  end

  # Display datetime without UTC suffix or just date
  def sent(short: false)
    short ? self[:sent]&.strftime("%Y-%m-%d") : self[:sent]&.to_s(:db)
  end

  def sent=(value)
    self[:sent] = value
    self[:token_hash] = self.class.digest(token)
  end

  def received(short: false)
    date_field(:received, short: short)
  end

  def renewed(short: false)
    date_field(:renewed, short: short)
  end

  # Approval requests are good for a week once the e-mail is sent.
  def expired?
    self[:sent].present? && self[:sent] < ApprovalRequest.expiration_date
  end

  # Expired or unsent
  def mailable?
    %i[unsent expired].include? renewal_state
  end

  def renewal_state
    return :renewed if self[:renewed].present?

    return :approved if self[:received].present?

    return :expired if expired?

    return :sent if self[:sent].present?

    :unsent
  end

  private

  def date_field(field, short: false)
    if short
      self[field]&.strftime("%Y-%m-%d")
    else
      self[field]&.to_s(:db)
    end
  end
end

app/controllers/approval_requests_controller.rb
# frozen_string_literal: true

class ApprovalRequestsController < ApplicationController
  before_action :fetch_requests, only: %i[show update edit]

  def create
    if params[:submit_requests]
      @added_users = add_requests(params[:ht_users])
      flash[:notice] = "Added #{"request".pluralize(@added_users.count)} for #{@added_users.join ", "}" if @added_users.count.positive?
      session[:added_users] = @added_users
    end
    if params[:submit_renewals]
      @renewed_users = add_renewals(params[:ht_users])
      flash[:notice] = "Renewed #{@renewed_users.join ", "}" if @renewed_users.count.positive?
      session[:renewed_users] = @renewed_users
    end
    if params[:delete_expired]
      deleted = delete_expired
      flash[:notice] = "Removed #{deleted} #{"request".pluralize(deleted)}"
    end
    redirect_to action: :index
  end

  def index
    requests = ApprovalRequest.order("approver")
    @incomplete_reqs = requests.not_renewed.map { |r| ApprovalRequestPresenter.new(r) }
    @complete_reqs = requests.renewed.map { |r| ApprovalRequestPresenter.new(r) }
    @added_users = session[:added_users] || []
    @renewed_users = session[:renewed_users] || []
    session.delete :added_users
    session.delete :renewed_users
  end

  def update
    begin
      ApprovalRequestMailer.with(reqs: @reqs, base_url: request.base_url, body: params[:email_body]).approval_request_email.deliver_now
      @reqs.each do |req|
        next unless req.mailable?

        UserMailer.with(req: req).approval_request_user_email.deliver_now
        req.sent = Time.zone.now
        req.save!
      end
      flash[:notice] = "Messages sent"
    rescue => e
      flash[:alert] = e.message
    end
    redirect_to action: "show"
  end

  def status_counts
    @reqs.group_by(&:renewal_state).transform_values(&:length)
  end

  def edit
    @preview = true
    @email_body = render_to_string partial: "shared/approval_request_body"
  end

  private

  def fetch_requests
    @reqs = ApprovalRequest.for_approver(params[:id]).not_renewed.map do |r|
      ApprovalRequestPresenter.new(r)
    end
  end

  # Add an approval request for selected users.
  # If unrenewed one already exists, silently skip over it.
  # Returns an Array of ht_user emails added to requests.
  def add_requests(emails)
    if emails.nil? || emails.empty?
      flash[:alert] = "No users selected"
      return []
    end
    adds = []
    emails.each do |e|
      next if ApprovalRequest.where(userid: e, renewed: nil).count.positive?

      begin
        add_request e
        adds << e
      rescue => e
        flash[:alert] = e.message
      end
    end
    adds
  end

  def add_request(email)
    u = HTUser.find(email)
    ApprovalRequest.new(ht_user: u, approver: u.approver).save!
  end

  def add_renewals(emails)
    if emails.nil? || emails.empty?
      flash[:alert] = "No users selected"
      return []
    end
    adds = []
    emails.each do |e|
      HTUser.find(e).add_or_update_renewal(approver: current_user.id)
      adds << e
    rescue => e
      flash[:alert] = e.message
    end
    adds
  end

  def delete_expired
    ApprovalRequest.expired.destroy_all.count
  end
end

app/views/approval_requests/edit.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>

<div id="maincontent" class="row">
  <h1>Approval Requests for <%= params[:id] %></h1>

  <%= render 'shared/flash_message' %>
  <% if @reqs.count == 0 %>
    There are no outstanding requests for this approver.
  <% else %>
  <ul class="list-group">
    <% @reqs.each do |req| %>
      <li class="list-group-item">
        <%= req.userid %>
        <%= req.badge %>
      </li>
    <% end %>
    </ul>
    <!-- MAIL PREVIEW -->
    <% counts = controller.status_counts %>
    <% if counts[:unsent]&.positive? || counts[:expired]&.positive? %>
      <%= form_tag approval_request_path, method: :put do %>
        <div class="panel panel-default">
          <div class="panel-heading">E-mail Preview</div>
          <div class="panel-body">
            <%= cktext_area_tag :email_body, @email_body, ckeditor: { height: '325px' } %>
          </div>
          <div class="panel-body">
            <%= render 'shared/approval_request_user_table' %>
          </div>
        </div>
        <% label = counts[:expired]&.positive? ? 'RESEND' : 'SEND' %>
        <%= submit_tag label, class: 'btn btn-primary' %>
        <%= link_to 'Cancel', approval_request_path(@reqs[0].approver), class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/approval_requests/index.html.erb
<div id="maincontent" class="row">
  <h1>Approval Requests</h1>
  <% if can?(:edit, :approval_requests) %>
    <p>To edit and send an approval request email, click on an approver email.</p>
  <% end %>

  <%= render 'shared/flash_message' %>

  <%= form_tag(approval_requests_path, method: :post) do %>
  <h2 class="pull-left">Active Requests</h2>
  <table id="active_users" class="table table-striped" data-toggle="table" data-height="460" data-virtual-scroll="true"
         data-search="true" data-show-search-clear-button="true">
    <thead class="thead-dark">
    <tr>
      <th data-sortable="false">Select</th>
      <th data-sortable="true">Approver</th>
      <th data-sortable="true">User</th>
      <th data-sortable="true">Sent</th>
      <th data-sortable="true">Approved</th>
      <th data-sortable="true">Renewed</th>
    </tr>
    </thead>

    <% @incomplete_reqs.each do |req| %>
      <%= tag(:tr, class: @added_users.include?(req.userid) ? :success : nil) %>
        <td>
          <% if can?(:edit, :approval_requests) %>
            <%= req.select_for_renewal_checkbox %>
          <% end %>
        </td>
        <td>
          <% if can?(:edit, :approval_requests) %>
            <%= req.approver_link %>
          <% else %>
            <%= req.approver %>
          <% end %>
        </td>
        <td>
          <%= req.userid_link(label: can?(:edit, :approval_requests)) %>
        </td>
        <td class="text-nowrap">
          <%= req.sent(short: true) %>
          <% if req.renewal_state == :expired %>
            <%= req.badge %>
          <% end %>
        </td>
        <td><%= req.received(short: true) %></td>
        <td><%= req.renewed(short: true) %></td>
      </tr>
    <% end %>
  </table>
  <br/>
  <% if can?(:edit, :ht_users) %>
    <%= submit_tag 'Renew Selected Users', name: 'submit_renewals', class: 'btn btn-primary' %>
  <% end %>
  <% if can?(:destroy, :approval_requests) && ApprovalRequest.expired.any? %>
    <%= submit_tag 'Delete Expired Requests', name: 'delete_expired', class: 'btn btn-danger',
                   data: { confirm: "Please confirm deletion of #{ApprovalRequestPresenter.expired_requests}." } %>
  <% end %>
  <% end # form-tag %>
  <h2 class="pull-left">Inactive Requests</h2>
  <table id="inactive_users" class="table table-striped" data-toggle="table" data-height="460" data-virtual-scroll="true"
         data-search="true" data-show-search-clear-button="true">
    <thead class="thead-dark">
    <tr>
      <th data-sortable="true">Approver</th>
      <th data-sortable="true">User</th>
      <th data-sortable="true">Sent</th>
      <th data-sortable="true">Approved</th>
      <th data-sortable="true">Renewed</th>
    </tr>
    </thead>

    <% @complete_reqs.each do |req| %>
      <%= tag(:tr, class: @renewed_users.include?(req.userid) ? :success : nil) %>
        <td><%= req.approver %></td>
        <td><%= link_to req.userid, ht_user_path(req.userid) %></td>
        <td><%= req.sent(short: true) %></td>
        <td><%= req.received(short: true) %></td>
        <td><%= req.renewed(short: true) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/approval_requests/show.html.erb
<div id="maincontent" class="row">
  <h1>Approval Requests for <%= params[:id] %></h1>

  <%= render 'shared/flash_message' %>
  <% if @reqs.count == 0 %>
    There are no outstanding requests for this approver.
  <% else %>
    <ul class="list-group">
    <% @reqs.each do |req| %>
      <li class="list-group-item">
        <%= req.userid %>
        <%= req.badge %>
      </li>
    <% end %>
    </ul>
    <% counts = controller.status_counts %>
    <% if counts[:unsent]&.positive? || counts[:expired]&.positive? %>
      <%= link_to 'Edit', edit_approval_request_path, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>